# Jekyll
permalink: /:categories/:title/
exclude: 
name: Pallet, DevOps for the JVM
pygments: true
domain: palletops.com
navigation:
- text: Overview
  active: false
  url: /doc/overview
  sections: [overview]
- text: About
  active: false
  url: /about
- text: Documentation
  active: true
  url: /doc
  sections: [doc, documentation]
- text: News
  active: true
  url: /news
  sections: [news]
- text: Blog
  active: true
  url: /blog
  sections: [blog]
- text: Get the Code!
  active: true
  url: http://github.com/pallet/pallet
- text: Getting Started
  active: false
  url: /doc/getting-started

- text: Community
  active: false
  url: /community