# Jekyll
permalink: /:categories/:title/
exclude: [release.sh]
name: Pallet, DevOps for the JVM
pygments: true
domain: palletops.com
description: Pallet is a platform for agile and programmatic automation of 
   infrastructure in the cloud, on server racks or directly on virtual machines. 
navigation:
- text: Overview
  active: false
  url: /doc/overview
  sections: [overview]  
- text: About
  active: false
  url: /about
- text: Documentation
  active: true
  url: /doc
  sections: [doc, documentation]
- text: News
  active: true
  url: /news
  sections: [news]
- text: Blog
  active: true
  url: /blog
  sections: [blog]
- text: Code
  active: true
  url: https://github.com/pallet/pallet
- text: Support
  active: true
  url: https://palletops.zendesk.com/anonymous_requests/new
- text: Contact
  active: true
  url: http://palletops.wufoo.com/forms/contact-palletops/
- text: Getting Started
  active: false
  url: /doc/getting-started
- text: Community
  active: false
  url: /community
